websockets_experiment/ws/config/routes.rb
Ws::Application.routes.draw do

  root 'welcome#index'

  resources :chat

end

websockets_experiment/ws/app/models/chat.rb
class Chat < ActiveRecord::Base
  has_many :chat_messages
  has_many :users, through: :chat_messages
end

websockets_experiment/ws/app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  belongs_to :user
  belongs_to :chat
end

websockets_experiment/ws/app/models/user.rb
class User < ActiveRecord::Base
  has_many :chat_messages
  has_many :chats, through: :chat_messages
end

websockets_experiment/ws/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

websockets_experiment/ws/app/controllers/chat_controller.rb
class ChatController < ApplicationController

  def new

  end

  def create

  end

  def update

  end

end

websockets_experiment/ws/app/controllers/chat_messages_controller.rb
class ChatMessagesController < WebsocketRails::BaseController
  def initialize_session
    controller_store[:message_count] = 0
  end

  def broadcast
    puts 'in broadcast'
    puts message
    # notification = "Hey clients, this is the server!"
    broadcast_message :notification, message, namespace: 'chat_messages'
  end

end

  # def create
  #   if can? :create, ChatMessage
  #     chat_message = ChatMessage.create(event.data) do |message|
  #       message.user = current_user
  #     end
  #     if chat_message
  #       @messages_sent +=  1
  #       trigger_success( message: 'Message created')
  #       broadcast_message :created, chat_message,
  #         namespace: :chat_messages
  #     else
  #       trigger_failure( message: chat_message.error.full_messages.join(' ') )
  #     end
  #   else
  #     trigger_failure( message: 'Unauthorized' )
  #   end
  # end

websockets_experiment/ws/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end


end

websockets_experiment/ws/app/helpers/application_helper.rb
module ApplicationHelper
end

websockets_experiment/ws/app/views/chat/new.html.erb
<h1>The Chat Page!</h1>
<div id="chat_window"></div>
<a href='#'><button id="start_chat">Start Chat!</button></a>
  <%= form_for '@task', url: {action: 'create'}, html: {class: "chat_form"} do |f| %>
  <p>
    <%= f.text_area :user_input, size: "60x3" %>
  </p>
  <p>
    <%= f.submit "Send" %>
  </p>
<% end %>

websockets_experiment/ws/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ws</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

websockets_experiment/ws/app/views/welcome/index.html.erb
<%= button_to "Go to Chat Page", new_chat_path, method: "get" %>